import type { ISDK, SDKCategory } from '../types/sdk.types';

export const SDK_LIST: ISDK[] = [
  // Web SDKs
  {
    id: 'web-js',
    name: 'Web.js',
    category: 'web',
    version: '1.0.0',
    description: 'HTML · JavaScript SDK for web integration',
    documentationUrl: 'https://docs.pwc.com/web-js',
    downloadUrl: 'https://github.com/pwc/web-js/releases',
    githubUrl: 'https://github.com/pwc/web-js',
    language: 'JavaScript',
    platform: 'Web',
  },
  {
    id: 'react-sdk',
    name: 'React SDK',
    category: 'web',
    version: '1.0.0',
    description: 'React components for PWC integration',
    documentationUrl: 'https://docs.pwc.com/react',
    downloadUrl: 'https://github.com/pwc/react-sdk/releases',
    githubUrl: 'https://github.com/pwc/react-sdk',
    language: 'TypeScript',
    platform: 'React',
  },
  // Server-side SDKs
  {
    id: 'node-sdk',
    name: 'Node.js SDK',
    category: 'server',
    version: '1.0.0',
    description: 'Node.js library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/node',
    downloadUrl: 'https://github.com/pwc/node-sdk/releases',
    githubUrl: 'https://github.com/pwc/node-sdk',
    language: 'JavaScript',
    platform: 'Node.js',
  },
  {
    id: 'python-sdk',
    name: 'Python SDK',
    category: 'server',
    version: '1.0.0',
    description: 'Python library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/python',
    downloadUrl: 'https://github.com/pwc/python-sdk/releases',
    githubUrl: 'https://github.com/pwc/python-sdk',
    language: 'Python',
    platform: 'Python',
  },
  {
    id: 'php-sdk',
    name: 'PHP SDK',
    category: 'server',
    version: '1.0.0',
    description: 'PHP library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/php',
    downloadUrl: 'https://github.com/pwc/php-sdk/releases',
    githubUrl: 'https://github.com/pwc/php-sdk',
    language: 'PHP',
    platform: 'PHP',
  },
  {
    id: 'java-sdk',
    name: 'Java SDK',
    category: 'server',
    version: '1.0.0',
    description: 'Java library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/java',
    downloadUrl: 'https://github.com/pwc/java-sdk/releases',
    githubUrl: 'https://github.com/pwc/java-sdk',
    language: 'Java',
    platform: 'Java',
  },
  {
    id: 'go-sdk',
    name: 'Go SDK',
    category: 'server',
    version: '1.0.0',
    description: 'Go library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/go',
    downloadUrl: 'https://github.com/pwc/go-sdk/releases',
    githubUrl: 'https://github.com/pwc/go-sdk',
    language: 'Go',
    platform: 'Go',
  },
  {
    id: 'ruby-sdk',
    name: 'Ruby SDK',
    category: 'server',
    version: '1.0.0',
    description: 'Ruby library for server-side integration',
    documentationUrl: 'https://docs.pwc.com/ruby',
    downloadUrl: 'https://github.com/pwc/ruby-sdk/releases',
    githubUrl: 'https://github.com/pwc/ruby-sdk',
    language: 'Ruby',
    platform: 'Ruby',
  },
  // Mobile SDKs
  {
    id: 'ios-sdk',
    name: 'iOS SDK',
    category: 'mobile',
    version: '1.0.0',
    description: 'iOS SDK for native iOS apps',
    documentationUrl: 'https://docs.pwc.com/ios',
    downloadUrl: 'https://github.com/pwc/ios-sdk/releases',
    githubUrl: 'https://github.com/pwc/ios-sdk',
    language: 'Swift',
    platform: 'iOS',
  },
  {
    id: 'android-sdk',
    name: 'Android SDK',
    category: 'mobile',
    version: '1.0.0',
    description: 'Android SDK for native Android apps',
    documentationUrl: 'https://docs.pwc.com/android',
    downloadUrl: 'https://github.com/pwc/android-sdk/releases',
    githubUrl: 'https://github.com/pwc/android-sdk',
    language: 'Kotlin',
    platform: 'Android',
  },
  {
    id: 'react-native-sdk',
    name: 'React Native SDK',
    category: 'mobile',
    version: '1.0.0',
    description: 'React Native SDK for cross-platform mobile apps',
    documentationUrl: 'https://docs.pwc.com/react-native',
    downloadUrl: 'https://github.com/pwc/react-native-sdk/releases',
    githubUrl: 'https://github.com/pwc/react-native-sdk',
    language: 'TypeScript',
    platform: 'React Native',
  },
];

export const SDK_CATEGORIES: { value: SDKCategory; label: string }[] = [
  { value: 'web', label: 'Web SDKs' },
  { value: 'server', label: 'Server-side SDKs' },
  { value: 'mobile', label: 'Mobile SDKs' },
  { value: 'community', label: 'Community SDKs' },
];
