export const ROUTES = {
  HOME: '/',
  REGISTER: '/register',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  LINK_EXPIRED: '/link-expired',
  VERIFIED_EMAIL: '/verified-email',
  ACTIVE: '/active',
  DASHBOARD: '/dashboard',
  BALANCE: '/balance',
  TRANSACTIONS: '/transactions',
  WALLET_ADDRESS: '/wallet-address',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  SYSTEM: '/settings/system',
  DEVELOPER: '/developer',
  NOT_FOUND: '/404',
  MERCHANTS: '/merchants',
  MERCHANT_DETAILS: '/merchants/$merchantId',
  TRANSACTION_DETAIL: '/transactions/$transactionId',
  GETTING_STARTED: "/getting-started"
} as const;
