export const KEYS = {
  WALLET_ADDRESS: 'merchants/wallet-addresses',
  WALLET_ADDRESS_DETAIL: 'merchants/wallet-addresses/:id',
  LOGIN: 'merchants/login',
  REGISTER: 'merchants/register',
  REFRESH_TOKEN: 'merchants/refresh-token',
  VERIFY: 'merchants/verify',
  RESEND_VERIFICATION: 'merchants/resend-verification',
  UPDATE_PASSWORD: 'merchants/password',
  FORGOT_PASSWORD: 'merchants/forgot-password',
  RESET_PASSWORD: 'merchants/reset-password',
  TWO_FA_VERIFY: 'merchants/2fa/verify',
  TWO_FA_VERIFY_SETUP: 'merchants/2fa/verify-setup',
  TWO_FA_VERIFY_SESSION: 'merchants/2fa/verify-session',
  TWO_FA_SETUP: 'merchants/2fa/setup',
  TWO_FA_DISABLE: 'merchants/2fa/disable',
  INFO: 'merchants/info',
  MARKETPLACE_INFO: 'marketplaces/info',
  SIGN_OUT: 'merchants/signout',
};
