/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormRouteImport } from './routes/demo/form'
import { Route as privateWalletAddressRouteImport } from './routes/(private)/wallet-address'
import { Route as privateDeveloperRouteImport } from './routes/(private)/developer'
import { Route as privateDashboardRouteImport } from './routes/(private)/dashboard'
import { Route as privateBalanceRouteImport } from './routes/(private)/balance'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authVerifiedEmailRouteImport } from './routes/(auth)/verified-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authLinkExpiredRouteImport } from './routes/(auth)/link-expired'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authActiveRouteImport } from './routes/(auth)/active'
import { Route as privateMerchantsLayoutRouteImport } from './routes/(private)/merchants/layout'
import { Route as privateTransactionsIndexRouteImport } from './routes/(private)/transactions/index'
import { Route as privateSettingsIndexRouteImport } from './routes/(private)/settings/index'
import { Route as privateMerchantsIndexRouteImport } from './routes/(private)/merchants/index'
import { Route as privateTransactionsTransactionIdRouteImport } from './routes/(private)/transactions/$transactionId'
import { Route as privateSettingsSystemRouteImport } from './routes/(private)/settings/system'
import { Route as privateSettingsProfileRouteImport } from './routes/(private)/settings/profile'
import { Route as privateMerchantsMerchantIdRouteImport } from './routes/(private)/merchants/$merchantId'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const privateWalletAddressRoute = privateWalletAddressRouteImport.update({
  id: '/wallet-address',
  path: '/wallet-address',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDeveloperRoute = privateDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDashboardRoute = privateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateBalanceRoute = privateBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => privateLayoutRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authLayoutRoute,
} as any)
const authVerifiedEmailRoute = authVerifiedEmailRouteImport.update({
  id: '/verified-email',
  path: '/verified-email',
  getParentRoute: () => authLayoutRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLinkExpiredRoute = authLinkExpiredRouteImport.update({
  id: '/link-expired',
  path: '/link-expired',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authActiveRoute = authActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => authLayoutRoute,
} as any)
const privateMerchantsLayoutRoute = privateMerchantsLayoutRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateTransactionsIndexRoute =
  privateTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateSettingsIndexRoute = privateSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateMerchantsIndexRoute = privateMerchantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateMerchantsLayoutRoute,
} as any)
const privateTransactionsTransactionIdRoute =
  privateTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateSettingsSystemRoute = privateSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateSettingsProfileRoute = privateSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateMerchantsMerchantIdRoute =
  privateMerchantsMerchantIdRouteImport.update({
    id: '/$merchantId',
    path: '/$merchantId',
    getParentRoute: () => privateMerchantsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/merchants': typeof privateMerchantsLayoutRouteWithChildren
  '/active': typeof authActiveRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/link-expired': typeof authLinkExpiredRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verified-email': typeof authVerifiedEmailRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/balance': typeof privateBalanceRoute
  '/dashboard': typeof privateDashboardRoute
  '/developer': typeof privateDeveloperRoute
  '/wallet-address': typeof privateWalletAddressRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/': typeof privateIndexRoute
  '/merchants/$merchantId': typeof privateMerchantsMerchantIdRoute
  '/settings/profile': typeof privateSettingsProfileRoute
  '/settings/system': typeof privateSettingsSystemRoute
  '/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/merchants/': typeof privateMerchantsIndexRoute
  '/settings': typeof privateSettingsIndexRoute
  '/transactions': typeof privateTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/active': typeof authActiveRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/link-expired': typeof authLinkExpiredRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verified-email': typeof authVerifiedEmailRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/balance': typeof privateBalanceRoute
  '/dashboard': typeof privateDashboardRoute
  '/developer': typeof privateDeveloperRoute
  '/wallet-address': typeof privateWalletAddressRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/': typeof privateIndexRoute
  '/merchants/$merchantId': typeof privateMerchantsMerchantIdRoute
  '/settings/profile': typeof privateSettingsProfileRoute
  '/settings/system': typeof privateSettingsSystemRoute
  '/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/merchants': typeof privateMerchantsIndexRoute
  '/settings': typeof privateSettingsIndexRoute
  '/transactions': typeof privateTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(private)': typeof privateLayoutRouteWithChildren
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/(private)/merchants': typeof privateMerchantsLayoutRouteWithChildren
  '/(auth)/active': typeof authActiveRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/link-expired': typeof authLinkExpiredRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verified-email': typeof authVerifiedEmailRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(private)/balance': typeof privateBalanceRoute
  '/(private)/dashboard': typeof privateDashboardRoute
  '/(private)/developer': typeof privateDeveloperRoute
  '/(private)/wallet-address': typeof privateWalletAddressRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/(private)/': typeof privateIndexRoute
  '/(private)/merchants/$merchantId': typeof privateMerchantsMerchantIdRoute
  '/(private)/settings/profile': typeof privateSettingsProfileRoute
  '/(private)/settings/system': typeof privateSettingsSystemRoute
  '/(private)/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/(private)/merchants/': typeof privateMerchantsIndexRoute
  '/(private)/settings/': typeof privateSettingsIndexRoute
  '/(private)/transactions/': typeof privateTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/404'
    | '/merchants'
    | '/active'
    | '/forgot-password'
    | '/link-expired'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified-email'
    | '/verify-email'
    | '/balance'
    | '/dashboard'
    | '/developer'
    | '/wallet-address'
    | '/demo/form'
    | '/demo/storybook'
    | '/'
    | '/merchants/$merchantId'
    | '/settings/profile'
    | '/settings/system'
    | '/transactions/$transactionId'
    | '/merchants/'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/404'
    | '/active'
    | '/forgot-password'
    | '/link-expired'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified-email'
    | '/verify-email'
    | '/balance'
    | '/dashboard'
    | '/developer'
    | '/wallet-address'
    | '/demo/form'
    | '/demo/storybook'
    | '/'
    | '/merchants/$merchantId'
    | '/settings/profile'
    | '/settings/system'
    | '/transactions/$transactionId'
    | '/merchants'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/(auth)'
    | '/(private)'
    | '/$'
    | '/404'
    | '/(private)/merchants'
    | '/(auth)/active'
    | '/(auth)/forgot-password'
    | '/(auth)/link-expired'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verified-email'
    | '/(auth)/verify-email'
    | '/(private)/balance'
    | '/(private)/dashboard'
    | '/(private)/developer'
    | '/(private)/wallet-address'
    | '/demo/form'
    | '/demo/storybook'
    | '/(private)/'
    | '/(private)/merchants/$merchantId'
    | '/(private)/settings/profile'
    | '/(private)/settings/system'
    | '/(private)/transactions/$transactionId'
    | '/(private)/merchants/'
    | '/(private)/settings/'
    | '/(private)/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  DemoFormRoute: typeof DemoFormRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/wallet-address': {
      id: '/(private)/wallet-address'
      path: '/wallet-address'
      fullPath: '/wallet-address'
      preLoaderRoute: typeof privateWalletAddressRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/developer': {
      id: '/(private)/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof privateDeveloperRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/dashboard': {
      id: '/(private)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/balance': {
      id: '/(private)/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof privateBalanceRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/verified-email': {
      id: '/(auth)/verified-email'
      path: '/verified-email'
      fullPath: '/verified-email'
      preLoaderRoute: typeof authVerifiedEmailRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/link-expired': {
      id: '/(auth)/link-expired'
      path: '/link-expired'
      fullPath: '/link-expired'
      preLoaderRoute: typeof authLinkExpiredRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/active': {
      id: '/(auth)/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof authActiveRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(private)/merchants': {
      id: '/(private)/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof privateMerchantsLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/transactions/': {
      id: '/(private)/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof privateTransactionsIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/settings/': {
      id: '/(private)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privateSettingsIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/merchants/': {
      id: '/(private)/merchants/'
      path: '/'
      fullPath: '/merchants/'
      preLoaderRoute: typeof privateMerchantsIndexRouteImport
      parentRoute: typeof privateMerchantsLayoutRoute
    }
    '/(private)/transactions/$transactionId': {
      id: '/(private)/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof privateTransactionsTransactionIdRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/settings/system': {
      id: '/(private)/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof privateSettingsSystemRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/settings/profile': {
      id: '/(private)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof privateSettingsProfileRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/merchants/$merchantId': {
      id: '/(private)/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof privateMerchantsMerchantIdRouteImport
      parentRoute: typeof privateMerchantsLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authActiveRoute: typeof authActiveRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLinkExpiredRoute: typeof authLinkExpiredRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifiedEmailRoute: typeof authVerifiedEmailRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authActiveRoute: authActiveRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLinkExpiredRoute: authLinkExpiredRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifiedEmailRoute: authVerifiedEmailRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface privateMerchantsLayoutRouteChildren {
  privateMerchantsMerchantIdRoute: typeof privateMerchantsMerchantIdRoute
  privateMerchantsIndexRoute: typeof privateMerchantsIndexRoute
}

const privateMerchantsLayoutRouteChildren: privateMerchantsLayoutRouteChildren =
  {
    privateMerchantsMerchantIdRoute: privateMerchantsMerchantIdRoute,
    privateMerchantsIndexRoute: privateMerchantsIndexRoute,
  }

const privateMerchantsLayoutRouteWithChildren =
  privateMerchantsLayoutRoute._addFileChildren(
    privateMerchantsLayoutRouteChildren,
  )

interface privateLayoutRouteChildren {
  privateMerchantsLayoutRoute: typeof privateMerchantsLayoutRouteWithChildren
  privateBalanceRoute: typeof privateBalanceRoute
  privateDashboardRoute: typeof privateDashboardRoute
  privateDeveloperRoute: typeof privateDeveloperRoute
  privateWalletAddressRoute: typeof privateWalletAddressRoute
  privateIndexRoute: typeof privateIndexRoute
  privateSettingsProfileRoute: typeof privateSettingsProfileRoute
  privateSettingsSystemRoute: typeof privateSettingsSystemRoute
  privateTransactionsTransactionIdRoute: typeof privateTransactionsTransactionIdRoute
  privateSettingsIndexRoute: typeof privateSettingsIndexRoute
  privateTransactionsIndexRoute: typeof privateTransactionsIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateMerchantsLayoutRoute: privateMerchantsLayoutRouteWithChildren,
  privateBalanceRoute: privateBalanceRoute,
  privateDashboardRoute: privateDashboardRoute,
  privateDeveloperRoute: privateDeveloperRoute,
  privateWalletAddressRoute: privateWalletAddressRoute,
  privateIndexRoute: privateIndexRoute,
  privateSettingsProfileRoute: privateSettingsProfileRoute,
  privateSettingsSystemRoute: privateSettingsSystemRoute,
  privateTransactionsTransactionIdRoute: privateTransactionsTransactionIdRoute,
  privateSettingsIndexRoute: privateSettingsIndexRoute,
  privateTransactionsIndexRoute: privateTransactionsIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  privateLayoutRoute: privateLayoutRouteWithChildren,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  DemoFormRoute: DemoFormRoute,
  DemoStorybookRoute: DemoStorybookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
