/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormRouteImport } from './routes/demo/form'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authVerifiedEmailRouteImport } from './routes/(auth)/verified-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authLinkExpiredRouteImport } from './routes/(auth)/link-expired'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authActiveRouteImport } from './routes/(auth)/active'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authLayoutRoute,
} as any)
const authVerifiedEmailRoute = authVerifiedEmailRouteImport.update({
  id: '/verified-email',
  path: '/verified-email',
  getParentRoute: () => authLayoutRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLinkExpiredRoute = authLinkExpiredRouteImport.update({
  id: '/link-expired',
  path: '/link-expired',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authActiveRoute = authActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => authLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/active': typeof authActiveRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/link-expired': typeof authLinkExpiredRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verified-email': typeof authVerifiedEmailRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesByTo {
  '/active': typeof authActiveRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/link-expired': typeof authLinkExpiredRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verified-email': typeof authVerifiedEmailRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(auth)/active': typeof authActiveRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/link-expired': typeof authLinkExpiredRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verified-email': typeof authVerifiedEmailRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/active'
    | '/forgot-password'
    | '/link-expired'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified-email'
    | '/verify-email'
    | '/demo/form'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/active'
    | '/forgot-password'
    | '/link-expired'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verified-email'
    | '/verify-email'
    | '/demo/form'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/(auth)/active'
    | '/(auth)/forgot-password'
    | '/(auth)/link-expired'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verified-email'
    | '/(auth)/verify-email'
    | '/demo/form'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  DemoFormRoute: typeof DemoFormRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/verified-email': {
      id: '/(auth)/verified-email'
      path: '/verified-email'
      fullPath: '/verified-email'
      preLoaderRoute: typeof authVerifiedEmailRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/link-expired': {
      id: '/(auth)/link-expired'
      path: '/link-expired'
      fullPath: '/link-expired'
      preLoaderRoute: typeof authLinkExpiredRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/active': {
      id: '/(auth)/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof authActiveRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authActiveRoute: typeof authActiveRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLinkExpiredRoute: typeof authLinkExpiredRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifiedEmailRoute: typeof authVerifiedEmailRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authActiveRoute: authActiveRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLinkExpiredRoute: authLinkExpiredRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifiedEmailRoute: authVerifiedEmailRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  DemoFormRoute: DemoFormRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
