/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormRouteImport } from './routes/demo/form'
import { Route as privateProfileRouteImport } from './routes/(private)/profile'
import { Route as privateDashboardRouteImport } from './routes/(private)/dashboard'
import { Route as authSuccessNotificationRouteImport } from './routes/(auth)/success-notification'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authGettingStartedRouteImport } from './routes/(auth)/getting-started'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as privateTransactionsIndexRouteImport } from './routes/(private)/transactions/index'
import { Route as privateTransactionsTransactionIdRouteImport } from './routes/(private)/transactions/$transactionId'
import { Route as privateSettingsProfileRouteImport } from './routes/(private)/settings/profile'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const privateProfileRoute = privateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDashboardRoute = privateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateLayoutRoute,
} as any)
const authSuccessNotificationRoute = authSuccessNotificationRouteImport.update({
  id: '/success-notification',
  path: '/success-notification',
  getParentRoute: () => authLayoutRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)
const authGettingStartedRoute = authGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const privateTransactionsIndexRoute =
  privateTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateTransactionsTransactionIdRoute =
  privateTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => privateLayoutRoute,
  } as any)
const privateSettingsProfileRoute = privateSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/forgot-password': typeof authForgotPasswordRoute
  '/getting-started': typeof authGettingStartedRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/success-notification': typeof authSuccessNotificationRoute
  '/dashboard': typeof privateDashboardRoute
  '/profile': typeof privateProfileRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/': typeof privateIndexRoute
  '/settings/profile': typeof privateSettingsProfileRoute
  '/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/transactions/': typeof privateTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/forgot-password': typeof authForgotPasswordRoute
  '/getting-started': typeof authGettingStartedRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/success-notification': typeof authSuccessNotificationRoute
  '/dashboard': typeof privateDashboardRoute
  '/profile': typeof privateProfileRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/': typeof privateIndexRoute
  '/settings/profile': typeof privateSettingsProfileRoute
  '/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/transactions': typeof privateTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(private)': typeof privateLayoutRouteWithChildren
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/getting-started': typeof authGettingStartedRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/success-notification': typeof authSuccessNotificationRoute
  '/(private)/dashboard': typeof privateDashboardRoute
  '/(private)/profile': typeof privateProfileRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/(private)/': typeof privateIndexRoute
  '/(private)/settings/profile': typeof privateSettingsProfileRoute
  '/(private)/transactions/$transactionId': typeof privateTransactionsTransactionIdRoute
  '/(private)/transactions/': typeof privateTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/404'
    | '/forgot-password'
    | '/getting-started'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/success-notification'
    | '/dashboard'
    | '/profile'
    | '/demo/form'
    | '/demo/storybook'
    | '/'
    | '/settings/profile'
    | '/transactions/$transactionId'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/404'
    | '/forgot-password'
    | '/getting-started'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/success-notification'
    | '/dashboard'
    | '/profile'
    | '/demo/form'
    | '/demo/storybook'
    | '/'
    | '/settings/profile'
    | '/transactions/$transactionId'
    | '/transactions'
  id:
    | '__root__'
    | '/(auth)'
    | '/(private)'
    | '/$'
    | '/404'
    | '/(auth)/forgot-password'
    | '/(auth)/getting-started'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/success-notification'
    | '/(private)/dashboard'
    | '/(private)/profile'
    | '/demo/form'
    | '/demo/storybook'
    | '/(private)/'
    | '/(private)/settings/profile'
    | '/(private)/transactions/$transactionId'
    | '/(private)/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  DemoFormRoute: typeof DemoFormRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/dashboard': {
      id: '/(private)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(auth)/success-notification': {
      id: '/(auth)/success-notification'
      path: '/success-notification'
      fullPath: '/success-notification'
      preLoaderRoute: typeof authSuccessNotificationRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/getting-started': {
      id: '/(auth)/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof authGettingStartedRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(private)/transactions/': {
      id: '/(private)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof privateTransactionsIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/transactions/$transactionId': {
      id: '/(private)/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof privateTransactionsTransactionIdRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/settings/profile': {
      id: '/(private)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof privateSettingsProfileRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authGettingStartedRoute: typeof authGettingStartedRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSuccessNotificationRoute: typeof authSuccessNotificationRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authGettingStartedRoute: authGettingStartedRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSuccessNotificationRoute: authSuccessNotificationRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface privateLayoutRouteChildren {
  privateDashboardRoute: typeof privateDashboardRoute
  privateProfileRoute: typeof privateProfileRoute
  privateIndexRoute: typeof privateIndexRoute
  privateSettingsProfileRoute: typeof privateSettingsProfileRoute
  privateTransactionsTransactionIdRoute: typeof privateTransactionsTransactionIdRoute
  privateTransactionsIndexRoute: typeof privateTransactionsIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateDashboardRoute: privateDashboardRoute,
  privateProfileRoute: privateProfileRoute,
  privateIndexRoute: privateIndexRoute,
  privateSettingsProfileRoute: privateSettingsProfileRoute,
  privateTransactionsTransactionIdRoute: privateTransactionsTransactionIdRoute,
  privateTransactionsIndexRoute: privateTransactionsIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  privateLayoutRoute: privateLayoutRouteWithChildren,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  DemoFormRoute: DemoFormRoute,
  DemoStorybookRoute: DemoStorybookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
